// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kubajeenqrjhwwkhdfdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1YmFqZWVucXJqaHd3a2hkZmRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NjkxMjMsImV4cCI6MjA2NzM0NTEyM30.12ptOVROK_hjtw3X-LstPHtboimrWgS0iQHtQ889GEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});